use anyhow::Result;
use notify_debouncer_mini::notify::RecursiveMode;
use notify_debouncer_mini::{new_debouncer, DebouncedEvent};
use std::path::PathBuf;
use std::time::Duration;

/// How long to wait after the last change before re-dumping. Editing an entry usually touches the
/// file several times in quick succession (vim's write, the compileall check, the atomic move).
const DEBOUNCE: Duration = Duration::from_millis(600);

/// Watch the entries sources and regenerate the dump when they change.
///
/// The dump itself is produced by Python (the entries database is executable Python, and ~14 groups
/// are generated by function calls, so it cannot be read statically). That cost is paid here, off
/// the keystroke path, never during a search.
pub fn watch_entries(
    project_root: PathBuf,
    on_dump_ready: impl Fn() + Send + 'static,
) -> Result<Box<dyn std::any::Any>> {
    let actions = ps_core::Actions::resolve();

    let mut debouncer = new_debouncer(DEBOUNCE, move |result: Result<Vec<DebouncedEvent>, _>| {
        let Ok(events) = result else { return };
        if events.is_empty() {
            return;
        }

        match actions.dump_entries() {
            Ok(mut child) => match child.wait() {
                Ok(status) if status.success() => on_dump_ready(),
                Ok(status) => eprintln!("entries dump exited with {status}"),
                Err(error) => eprintln!("entries dump failed: {error}"),
            },
            Err(error) => eprintln!("could not run entries dump: {error}"),
        }
    })?;

    let entries_main = project_root.join("entries_main.py");
    if entries_main.exists() {
        debouncer
            .watcher()
            .watch(&entries_main, RecursiveMode::NonRecursive)?;
    }

    let entries_dir = project_root.join("entries");
    if entries_dir.exists() {
        debouncer
            .watcher()
            .watch(&entries_dir, RecursiveMode::Recursive)?;
    }

    Ok(Box::new(debouncer))
}

/// The entries project root, resolved the same way `ConfigurationLoader` does:
/// `PS_ENTRIES_HOME`, else the path recorded in `~/.config/python_search/current_project`.
pub fn entries_project_root() -> Option<PathBuf> {
    if let Ok(value) = std::env::var("PS_ENTRIES_HOME") {
        return Some(PathBuf::from(value));
    }
    let marker = dirs::home_dir()?.join(".config/python_search/current_project");
    let contents = std::fs::read_to_string(marker).ok()?;
    let path = contents.trim();
    if path.is_empty() {
        return None;
    }
    Some(PathBuf::from(path))
}
