[package]
name = "register_new_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
druid = "0.8"
serde = "1.0"
serde_json = "1.0"

[[bin]]
name = "register_new_rust"
path = "main.rs"

