[package]
name = "ps-mac"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
raw-window-handle = "0.6"

[target.'cfg(not(target_os = "macos"))'.dependencies]
libc = "0.2"

[target.'cfg(target_os = "macos")'.dependencies]
objc2 = "0.6"
objc2-foundation = { version = "0.3", features = ["NSString", "NSGeometry", "NSThread", "NSCalendar", "NSDate"] }
objc2-app-kit = { version = "0.3", features = [
    "NSWindow",
    "NSView",
    "NSVisualEffectView",
    "NSApplication",
    "NSResponder",
    "NSScreen",
    "NSColor",
    "NSGraphics",
    "NSRunningApplication",
    "NSWorkspace",
    "NSAppearance",
] }
dispatch2 = "0.3"
